### ISSUE TITLE
Use of `cdktf-tf-module-stack` instead of `@cdktf/tf-module-stack`

### ISSUE THREAD

**Issue by angabini** [cdktf/projen-cdktf-hybrid-construct#82]
### Description

After hitting some errors, one causing issue I believe is the use of `cdktf-tf-module-stack` instead of `@cdktf/tf-module-stack` in this project. 
The now old (seemingly not maintained) `cdktf-tf-module-stack` package gets installed into node-modules and appears in dependencies after a fresh `npx projen new --from projen-cdktf-hybrid-construct hybrid-module` and causes package dependency issues. This is most probably because its use in `https://github.com/cdktf/projen-cdktf-hybrid-construct/blob/main/src/hybrid-module.ts`.

I believe this needs to be replaced with `@cdktf/tf-module-stack`.

### Versions

language: null
cdktf-cli: 0.17.3
node: v18.16.1
terraform: 1.5.4
arch: arm64
os: darwin 22.5.0

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiehan** [comment]
Thanks for flagging! This should be fixed by #86 (release v4.0.0).

I also added a note to the README for tf-module-stack: https://github.com/cdktf/cdktf-tf-module-stack/blob/main/README.md#npm
